---
# tasks file for kentr.harden-wordpress

- name: Check for WordPress installation.
  stat:
    path: "{{ wp_harden_root }}/wp-config.php"
  register: wp_config

- name: Fail on invalid installation.
  fail:
    msg: |
      This doesn't appear to be a valid WordPress installation.
      Can't find {{ wp_harden_root }}/wp-config.php.
  when: wp_config.stat.isreg | default(False) == False

- name: Ensure `.htaccess` exists.
  template:
    # Don't replace existing file.
    force: no
    src: templates/.htaccess.j2
    dest: "{{ wp_harden_root }}/.htaccess"

- name: Block `wp-config.php`.
  blockinfile:
    dest:  "{{ wp_harden_root }}/.htaccess"
    create: no
    backup: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Block `wp-config.php`"
    insertbefore: "# BEGIN WordPress"
    state: present
    content: |
      # See https://codex.wordpress.org/Hardening_WordPress#WP-Config.php
      <files wp-config.php>
        order allow,deny
        deny from all
      </files>
  when: wp_harden_block_wpconfig

- name: Block the include-only files.
  blockinfile:
    dest:  "{{ wp_harden_root }}/.htaccess"
    create: no
    backup: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Block the include-only files"
    insertbefore: "# BEGIN WordPress"
    state: present
    content: |
      # See https://codex.wordpress.org/Hardening_WordPress#WP-Includes
      <IfModule mod_rewrite.c>
        RewriteEngine On
        RewriteBase /
        RewriteRule ^wp-admin/includes/ - [F,L]
        RewriteRule !^wp-includes/ - [S=3]
        RewriteRule ^wp-includes/[^/]+\.php$ - [F,L]
        RewriteRule ^wp-includes/js/tinymce/langs/.+\.php - [F,L]
        RewriteRule ^wp-includes/theme-compat/ - [F,L]
      </IfModule>
  when: wp_harden_block_include_only_files

- name: Block `debug.log`.
  blockinfile:
    dest:  "{{ wp_harden_root }}/.htaccess"
    create: no
    backup: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Block `debug.log`"
    insertbefore: "# BEGIN WordPress"
    state: present
    content: |
      <Files "debug.log">
        Order deny,allow
        Deny from all
      </Files>
  when: wp_harden_block_log_files

- name: Disable PHP execution in uploads directory.
  blockinfile:
    dest:  "{{ wp_harden_root }}/{{ wp_harden_uploads_dir | default('wp-content/uploads') }}/.htaccess"
    create: yes
    backup: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Kill PHP Execution"
    insertafter: EOF
    state: present
    content: |
      # See https://codex.wordpress.org/Hardening_WordPress#WP-Content.2FUploads
      <Files ~ "\.ph(?:p[345]?|t|tml)$">
         deny from all
      </Files>
  when: wp_harden_block_uploads_php

- name: Disable file editing.
  blockinfile:
    dest:  "{{ wp_harden_root }}/wp-config.php"
    create: no
    backup: yes
    marker: "// {mark} ANSIBLE MANAGED BLOCK: Disable file editing"
    insertbefore: ".*stop editing.*"
    state: present
    content: |
      // See https://codex.wordpress.org/Hardening_WordPress#Disable_File_Editing
      // Disable Editing in Dashboard
      define('DISALLOW_FILE_EDIT', true);
  when: wp_harden_disable_file_edits
